//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class competition
    {
        public competition()
        {
            this.competitionmatch = new HashSet<competitionmatch>();
        }
    
        public int CompetitionID { get; set; }
        public string CompetitionName { get; set; }
    
        public virtual ICollection<competitionmatch> competitionmatch { get; set; }
    }
}
