//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class matchgoal
    {
        public int MatchGoalID { get; set; }
        public int MatchID { get; set; }
        public int TeamID { get; set; }
        public int ScorerID { get; set; }
        public Nullable<int> AssistantID { get; set; }
        public Nullable<int> ScoringMinute { get; set; }
    
        public virtual competitionmatch competitionmatch { get; set; }
        public virtual player player { get; set; }
        public virtual player player1 { get; set; }
        public virtual team team { get; set; }
    }
}
