//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class matchodds
    {
        public int MatchOddsID { get; set; }
        public decimal HomeTeamOdds { get; set; }
        public decimal DrawOdds { get; set; }
        public decimal AwayTeamOdds { get; set; }
        public int MatchID { get; set; }
    
        public virtual competitionmatch competitionmatch { get; set; }
    }
}
