//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProjects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sakilaEntities4 : DbContext
    {
        public sakilaEntities4()
            : base("name=sakilaEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<actor> actor { get; set; }
        public DbSet<address> address { get; set; }
        public DbSet<category> category { get; set; }
        public DbSet<city> city { get; set; }
        public DbSet<competition> competition { get; set; }
        public DbSet<competitionmatch> competitionmatch { get; set; }
        public DbSet<country> country { get; set; }
        public DbSet<customer> customer { get; set; }
        public DbSet<eventtype> eventtype { get; set; }
        public DbSet<film> film { get; set; }
        public DbSet<film_actor> film_actor { get; set; }
        public DbSet<film_category> film_category { get; set; }
        public DbSet<film_text> film_text { get; set; }
        public DbSet<inventory> inventory { get; set; }
        public DbSet<language> language { get; set; }
        public DbSet<matchevent> matchevent { get; set; }
        public DbSet<matchgoal> matchgoal { get; set; }
        public DbSet<matchplayer> matchplayer { get; set; }
        public DbSet<payment> payment { get; set; }
        public DbSet<player> player { get; set; }
        public DbSet<playerposition> playerposition { get; set; }
        public DbSet<playertransfer> playertransfer { get; set; }
        public DbSet<rental> rental { get; set; }
        public DbSet<staff> staff { get; set; }
        public DbSet<store> store { get; set; }
        public DbSet<team> team { get; set; }
        public DbSet<teamtype> teamtype { get; set; }
    }
}
