//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class playerposition
    {
        public playerposition()
        {
            this.player = new HashSet<player>();
        }
    
        public int PlayerPositionID { get; set; }
        public string PlayerPositionName { get; set; }
    
        public virtual ICollection<player> player { get; set; }
    }
}
