//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public player()
        {
            this.matchgoal = new HashSet<matchgoal>();
            this.matchgoal1 = new HashSet<matchgoal>();
            this.matchplayer = new HashSet<matchplayer>();
            this.playertransfer = new HashSet<playertransfer>();
        }
    
        public int PlayerID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public int PositionID { get; set; }
        public string PlayerName { get; set; }
        public Nullable<int> NationalTeamID { get; set; }
    
        public virtual ICollection<matchgoal> matchgoal { get; set; }
        public virtual ICollection<matchgoal> matchgoal1 { get; set; }
        public virtual ICollection<matchplayer> matchplayer { get; set; }
        public virtual team team { get; set; }
        public virtual playerposition playerposition { get; set; }
        public virtual team team1 { get; set; }
        public virtual ICollection<playertransfer> playertransfer { get; set; }
    }
}
