//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class team
    {
        public team()
        {
            this.competitionmatch = new HashSet<competitionmatch>();
            this.competitionmatch1 = new HashSet<competitionmatch>();
            this.competitionmatch2 = new HashSet<competitionmatch>();
            this.matchevent = new HashSet<matchevent>();
            this.matchgoal = new HashSet<matchgoal>();
            this.matchplayer = new HashSet<matchplayer>();
            this.player = new HashSet<player>();
            this.player1 = new HashSet<player>();
            this.playertransfer = new HashSet<playertransfer>();
            this.playertransfer1 = new HashSet<playertransfer>();
        }
    
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> TeamTypeID { get; set; }
        public Nullable<int> MarketValue { get; set; }
    
        public virtual ICollection<competitionmatch> competitionmatch { get; set; }
        public virtual ICollection<competitionmatch> competitionmatch1 { get; set; }
        public virtual ICollection<competitionmatch> competitionmatch2 { get; set; }
        public virtual ICollection<matchevent> matchevent { get; set; }
        public virtual ICollection<matchgoal> matchgoal { get; set; }
        public virtual ICollection<matchplayer> matchplayer { get; set; }
        public virtual ICollection<player> player { get; set; }
        public virtual ICollection<player> player1 { get; set; }
        public virtual ICollection<playertransfer> playertransfer { get; set; }
        public virtual ICollection<playertransfer> playertransfer1 { get; set; }
        public virtual teamtype teamtype { get; set; }
    }
}
